### ISSUE TITLE
AllServices: Unification of ids referencing other Service Objects

### ISSUE THREAD

**Issue by NicolasVorwerg** [SamCooper/MC_SPEC_RIDS#179]
In each service there are operations or objects that are referencing other service-objects. (e.g. an Aggregation referencing Parameters). At the moment it changes if this reference is realised by the id of the definition or identity. But since the identity object was introduced, I think the object should always reference other service object by using their identity-id. The very exception should be the service-objects that have a "related" link to another object. 

Please have a look in all the existing composites for references. In the comment row of the fields that reference to other service objects, it has to be described that it references to the identity id. At the moment it is sometimes described to be the "definition", "object instance identifier", "object", or just the name of the service e.g. the "parameter to compare against". 

Here are some examples with corrections:

Composite: ParameterExpression:
field: parameterId; comment: "Identifies the parameter definition to be used in the expression"
change it to:
field: parameterId; comment: "Identifies the parameter identity to be used in the expression"

Composite: ReferenceValue:
field: parameterId; comment: "The parameter to compare against. [...]"
change it to:
field: parameterId; comment: "The identity id of the parameter to compare against. [...]"

Composite: CheckResultFilter:
field: parameterFilter; comment: "List of parameter object instance identifiers to filter on.[...]"
change it to:
field: parameterFilter; comment: "List of parameter identity ids to filter on.[...]"

If there is a special reason for not referencing the identity, there should be a short explanation why this is so. 

Please apply these changes in the standard.

**Comment by SamCooper** [comment]
Accepted

**Comment by SamCooper** [comment]
I have thought a little about this and the reason we brought in the change was to remove the ambiguity about which definition was being used for example by a check. I.e. so that a check link linked to a specific definition of a check and also a parameter.

However this has now cause the situation above where a small change in a parameter definition has a large cascade effect on all other objects that referenced that previous "old" definition.

The problem with using inferred definitions, ones that are determined based on timestamps, is that it relies on a unified system wide timestamp clock. Which no system has.

I am wondering if the basic rule should be that operation arguments should use the Identity objects (so effectively refer to "Param123" rather than "DefinitionXYZ") and by implication also use the latest definition, but the objects themselves will link to specific definition they are using. So they will report the correct definition object when queried, stored, or published.

I do not think we should avoid the cascade change issue, it is important that these happen. But I do not think we should report this change, this would happen when the objects in question next get published.

**Comment by SamCooper** [comment]
ok, further consideration on this and I think there may be a middle ground.

Basically, when objects are linking to each other (and those objects have a lifetime) then they should link to the identity. But when they are report (static) objects then they should include the definition details.

For example, currently the CheckLink object links to the ParameterDefinition object. That definition object holds the generationEnabled boolean. So if the parameter is enabled/disabled then a new definition is created which causes a cascade effect on the CheckLink object.

If the CheckLink object links to the ParameterIdentity object instead then the casecade would not happen. But we now have the problem, when a check transition event is generated, of not knowing which parameter definition it was using. the solution is to include the missing information in the check transition event information.

Does this make sense Nicolas?

**Comment by NicolasVorwerg** [comment]
> If the CheckLink object links to the ParameterIdentity object instead then the casecade would not happen. But we now have the problem, when a check transition event is generated, of not knowing which parameter definition it was using. the solution is to include the missing information in the check transition event information.

You are right. The state is depended on the definition. So its important to have the information about the  definition that was used for evaluating the result. So yes in this case an information containing the definition-id has to be added. Considering  #180 : the information which Actual Check Definition was used should be added as well.

> Basically, when objects are linking to each other (and those objects have a lifetime) then they should link to the identity. But when they are report (static) objects then they should include the definition details.

That's it!

**Comment by SamCooper** [comment]
So are we happy with this proposal?

**Comment by NicolasVorwerg** [comment]
I am happy

**Comment by SamCooper** [comment]
Ok, I'll write it up and present it at the meeting.

**Comment by SamCooper** [comment]
Done.
