### ISSUE TITLE
Update of the archive

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#38]
One of the requirements of the following operations : enablegeneration, enableCheck and enableFilter says that:

"The provider should update the [...]definition object"

One of the roles of the archive is to assure data persistence. Framed this way, the above requirement might lead to believe that the definition object in the archive is directly modified, which would result in the loss of the previous state of the definition. 

Would it not be  better  and more accurate to say " an update of the [...]definition object should be stored in the archive" ?

**Comment by SamCooper** [comment]
The new COM archive allows us to modify an object. But it does not work in the same way as the old COM archive/model which were really version control systems rather than databases.

So, the requirement is correct in that the original is modified. It is a loss of the previous state but that is ok as the changes are limited.

**Comment by SamCooper** [comment]
WG to review the list of modifiable attributes. SC to distribute the set of attributes of each service and their modifiable status.

**Comment by SamCooper** [comment]
Done
