### ISSUE TITLE
Checkdefinition structure

### ISSUE THREAD

**Issue by BEHAL** [SamCooper/MC_SPEC_RIDS#39]
Requirement a) of section 3.5.4 states that:

 a) Two COM objects shall be used to hold the check definition details, the first is a CheckDefinition COM object that holds the name of the check definition and a second COM object that holds the actual definition of the check. 

All the objects that hold the actual definition of the check extend the CheckDefinitionDetails structure. One of the fields of this structure is the field "name" whose meaning is, according to the comment, "the name of the check definition".

What is the link between the name of the checkDefinition in the CheckDefinition COM object and the name in the CheckDefinitionDetails ? Should they be identical ? If so, is there not a risk of inconsistency ?

Clarify please.

**Comment by SamCooper** [comment]
As they are referring to the same thing they should be identical however they should not be duplicated like this. I will remove one of them so that we don't have to add requirements to ensure that they are the same etc. but I need to check that it will not affect any of the operations.

I will look into this.

**Comment by SamCooper** [comment]
Done
